# CONSTANTS SETTING SECTION

## The current "RISC-V Week" edition.
RISCV_WEEK=2023-06

## The directories involved in producing the site content: SITE_SRC is
## where the web site's source files lives. SITE_PUB is the root of
## the public web site files, i.e. what is actually published
## online. SITE_TMP is where the site is generated by Haskyll, first
## for off line checking through a local ad-hoc Haskyll web sierver,
## then as the base of the final rsync to SITE_DIR. SITE_TMP a
## temporary directory and is not versioned by Git -- see .gitignore.
SITE_PUB=site.pub
SITE_TMP=site.tmp
SITE_SRC=site.src

HAKYLL_DIR=hakyll
HAKYLL_BIN=hakyll/.stack-work
HAKYLL_TMP=cache.tmp

## Better use the same branches for source code and published web
## pages.
SOURCE_BRANCH=master
ONLINE_BRANCH=master

## The files and directories that shall be removed when cleaning the
## local repo. Making clobber will include making clean.
CLEAN_LIST+=*~
CLEAN_LIST+=*/*~
CLEAN_LIST+=*/*/*~
CLOBBER_LIST+=$(SITE_TMP)
CLOBBER_LIST+=$(HAKYLL_TMP)
CLOBBER_LIST+=$(HAKYLL_BIN)
CLOBBER_LIST+=stack.yaml.lock


# HAKYLL WIZARDRY SECTION

## To build stack. Whatever that means...
.PHONY: stack-build
stack-build:
	( cd $(HAKYLL_DIR) ; stack build )

## To rebuild the Hakyll site compiler, and compile the site anew in
## $(SOURCE_TEMP_DIR).
.PHONY: rebuild-site
rebuild-site: stack-build
	( cd $(HAKYLL_DIR) ; stack exec site -- rebuild )

## To compile the site in $(SOURCE_TEMP_DIR) with the current Hakyll
## site compiler.
.PHONY: compile-site
compile-site: stack-build
	( cd $(HAKYLL_DIR) ; stack exec site -- build )

## To launch a local web server at http://127.0.0.1:8000 and help
## debug the site's contents.
.PHONY: watch-site
watch-site: stack-build
	( cd $(HAKYLL_DIR) ; stack exec site -- watch )


# Housekeeping

## Clean-up of the local repo.
.PHONY: clean
clean:
	rm -rf $(CLEAN_LIST)

.PHONY: clobber
clobber: clean
	rm -rf $(CLOBBER_LIST)

## Dump all variables for debug.
.PHONY: variables
variables: \
	_print_RISCV_WEEK \
	_print_SITE_SRC \
	_print_SITE_TMP \
	_print_SITE_PUB\
	_print_HAKYLL_DIR \
	_print_HAKYLL_BIN \
	_print_HAKYLL_TMP \
	_print_SOURCE_BRANCH \
	_print_ONLINE_BRANCH \
	_print_CLEAN_LIST \
	_print_CLOBBER_LIST \

_print_%:
	@/bin/echo '$*=$($*)'
